const ConstantType = {
    ADD_POST: 'ADD_POST',
    UPDATE_NEW_POST_TEXT: 'UPDATE_NEW_POST_TEXT',
    SEND_MESSAGE: 'SEND_MESSAGE',
    UPDATE_NEW_MESSAGE_TEXT: 'UPDATE_NEW_MESSAGE_TEXT',
    FOLLOW: 'FOLLOW',
    UNFOLLOW: 'UNFOLLOW',
    SET_USERS: 'SET_USERS',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_TOTAL_COUNT: 'SET_TOTAL_COUNT',
    UPDATE_USERS: 'UPDATE_USERS',
    SET_SEARCH_USERS: 'SET_SEARCH_USERS',
    SET_SEARCH_USERS_TOTAL_COUNT: 'SET_SEARCH_USERS_TOTAL_COUNT',
    SET_SEARCH_USERS_NAME: 'SET_SEARCH_USERS_NAME',
    RESET_SEARCH_USERS_NAME: 'RESET_SEARCH_USERS_NAME',
    SET_COUNT_USERS: 'SET_COUNT_USERS',
    SET_USER_INFO: 'SET_USER_INFO',
    SET_LOGIN: 'SET_LOGIN',
    SET_STATUS_LOGIN: 'SET_STATUS_LOGIN',
    SET_MESSAGE_LOGIN: 'SET_MESSAGE_LOGIN',
    SET_IS_AUTH: 'SET_IS_AUTH',
    SET_USER_INFO_AUTH: 'SET_USER_INFO_AUTH',
    SET_USER_AVATAR_URL: 'SET_USER_AVATAR_URL',
    SET_MESSAGE_ERROR_AUTH: 'SET_MESSAGE_ERROR_AUTH',
    SET_ID: 'SET_ID'
};

export default ConstantType;